name: Rave-Up
title: Rave-Up Records
description: "Obscure nuggets from the golden age of ROCK'n ROLL"
repository: raveup/raveup.github.io
logo: /assets/images/logo2019.png
baseurl:
permalink: /:categories/:title
excerpt_separator: "\n\n"
relative_permalinks: false
exclude: [ php ]
url: https://www.raveuprecords.com
timezone: Europe/Rome
plugins:
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-titles-from-headings
sass:
  sass_dir: _sass
  style: compressed
script:
  - js/jquery.min.js
  - js/jquery.ui.totop.js
  - js/easing.js
  - js/main.js
  - js/md5.min.js
  - js/buttons.js
  - js/carello.js
collections:
  blog:
    output: true