# OUTDATE General for posts tagged `new`
# override in post with `outdate: ...`
outdate: OUT 15th OCTOBER 2016 !

# Blog Announcements to show
announcements: 1

# Site root url
root: http://www.raveuprecords.com
